language: python
python:
    - "3.8"

services:
    - docker

before_install:
  - docker --version

install:
  - pip install -r requirements.txt

deploy:
    provider: script
    script: bash deploy.sh
    on:
        branch: main